[package]
name = "hana-table-defs"
version = "0.1.0"
authors = ["Peggy Liang <pgl1998@proton.me>"]
edition = "2018"
description = "Table definitions for Hana Ethereum client"
license = "Apache-2.0"

[dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
